const demoData = [
  { _id: "demo-1", source: "demo", disease: "Influenza", location: "Madison, WI", lat: 43.0731, lng: -89.4012, cases: 18, date: "2026-08-27", symptomOnsetDate: "2026-08-24", ageGroup: "18-49", sex: "Unknown", facility: "Community clinic", suspectedExposure: "Seasonal respiratory exposure in outpatient setting.", status: "Confirmed", priority: "Low", reportSource: "Clinic report", notes: "Seasonal respiratory cluster reported by outpatient clinic." },
  { _id: "demo-2", source: "demo", disease: "COVID-19", location: "Chicago, IL", lat: 41.8781, lng: -87.6298, cases: 42, date: "2026-08-30", symptomOnsetDate: "2026-08-28", ageGroup: "50-64", sex: "Unknown", facility: "Regional laboratory", suspectedExposure: "Multiple linked positives from routine respiratory testing.", status: "Under Review", priority: "Medium", reportSource: "Laboratory report", notes: "Multiple positive tests submitted for review." },
  { _id: "demo-3", source: "demo", disease: "Measles", location: "Milwaukee, WI", lat: 43.0389, lng: -87.9065, cases: 7, date: "2026-09-01", symptomOnsetDate: "2026-08-29", ageGroup: "5-17", sex: "Unknown", facility: "School health office", suspectedExposure: "Possible school exposure event.", status: "New", priority: "High", reportSource: "School report", notes: "Possible exposure event requires confirmation." },
  { _id: "demo-4", source: "demo", disease: "Norovirus", location: "Minneapolis, MN", lat: 44.9778, lng: -93.265, cases: 33, date: "2026-09-02", symptomOnsetDate: "2026-09-01", ageGroup: "65+", sex: "Unknown", facility: "Long-term care facility", suspectedExposure: "Congregate dining exposure under investigation.", status: "Confirmed", priority: "Medium", reportSource: "Facility report", notes: "Gastrointestinal illness reported in congregate setting." },
  { _id: "demo-5", source: "demo", disease: "Influenza", location: "Detroit, MI", lat: 42.3314, lng: -83.0458, cases: 24, date: "2026-08-24", symptomOnsetDate: "2026-08-21", ageGroup: "18-49", sex: "Unknown", facility: "Primary care network", suspectedExposure: "Routine seasonal respiratory spread.", status: "Closed", priority: "Low", reportSource: "Clinic report", notes: "Follow-up completed; no escalation required." },
  { _id: "demo-6", source: "demo", disease: "COVID-19", location: "Indianapolis, IN", lat: 39.7684, lng: -86.1581, cases: 19, date: "2026-09-03", symptomOnsetDate: "2026-08-31", ageGroup: "18-49", sex: "Unknown", facility: "Community reporting line", suspectedExposure: "Community reports pending verification.", status: "Under Review", priority: "Low", reportSource: "Self report", notes: "Community reports pending verification." },
  { _id: "demo-7", source: "demo", disease: "Malaria", location: "Dakar, Senegal", lat: 14.7167, lng: -17.4677, cases: 57, date: "2026-08-29", symptomOnsetDate: "2026-08-25", ageGroup: "5-17", sex: "Unknown", facility: "District surveillance team", suspectedExposure: "Localized vector exposure after heavy rainfall.", status: "Confirmed", priority: "High", reportSource: "Field report", notes: "Elevated case volume flagged for field response." },
  { _id: "demo-8", source: "demo", disease: "Cholera", location: "Banjul, The Gambia", lat: 13.4549, lng: -16.579, cases: 12, date: "2026-09-04", symptomOnsetDate: "2026-09-02", ageGroup: "Unknown", sex: "Unknown", facility: "Community health post", suspectedExposure: "Potential waterborne exposure.", status: "New", priority: "High", reportSource: "Community report", notes: "Waterborne illness signal requires rapid verification." },
  { _id: "demo-9", source: "demo", disease: "Dengue", location: "Miami, FL", lat: 25.7617, lng: -80.1918, cases: 28, date: "2026-09-05", symptomOnsetDate: "2026-09-01", ageGroup: "18-49", sex: "Unknown", facility: "Hospital emergency department", suspectedExposure: "Travel-related and local vector exposure under review.", status: "Under Review", priority: "Medium", reportSource: "Hospital report", notes: "Travel-related cases under epidemiology review." },
  { _id: "demo-10", source: "demo", disease: "Influenza", location: "Toronto, Canada", lat: 43.6532, lng: -79.3832, cases: 31, date: "2026-08-31", symptomOnsetDate: "2026-08-27", ageGroup: "50-64", sex: "Unknown", facility: "Sentinel clinic network", suspectedExposure: "Respiratory activity above baseline.", status: "Confirmed", priority: "Medium", reportSource: "Clinic report", notes: "Respiratory activity above baseline." },
  { _id: "demo-11", source: "demo", disease: "COVID-19", location: "New York, NY", lat: 40.7128, lng: -74.006, cases: 68, date: "2026-09-06", symptomOnsetDate: "2026-09-03", ageGroup: "18-49", sex: "Unknown", facility: "Regional laboratory", suspectedExposure: "High-volume laboratory signal.", status: "Confirmed", priority: "High", reportSource: "Laboratory report", notes: "High-volume report with confirmed laboratory signal." },
  { _id: "demo-12", source: "demo", disease: "Norovirus", location: "Columbus, OH", lat: 39.9612, lng: -82.9988, cases: 16, date: "2026-09-07", symptomOnsetDate: "2026-09-06", ageGroup: "65+", sex: "Unknown", facility: "Assisted living facility", suspectedExposure: "New facility report awaiting review.", status: "New", priority: "Medium", reportSource: "Facility report", notes: "New facility report awaiting review." },
];

export default demoData;
